### ISSUE TITLE
Provide link to edition website from the Readme.md in this repo? 

### ISSUE THREAD

**Issue by ebeshero** [MKlamer/Motherhood-Journal#14]
@MKlamer You might provide a link to your website from this GitHub repo to help connect the two, for any who (like us coders and edition developers) find our way to your project via GitHub! Try adding a link to the Readme.md file on your repo, and maybe on the description that appears at the top of the Code view.

**Comment by MKlamer** [comment]
Thank you for the suggestion! I should have thought of that.
